name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:



    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 1.8

    - name: Restore Gradle user env && Update API KEY from Secrets
      env:
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      shell: bash
      run: |
       run: echo UNSPLASH_API_KEY="$UNSPLASH_API_KEY" > ./local.properties
       echo android.enableJetifier=true > ./gradle.properties
       echo android.useAndroidX=true >  ./gradle.properties

    - name: Read package.json
      uses: juliangruber/read-file-action@v1
      with:
        path: ./local.properties
    - name: Echo local.properties
      run: echo "${{ steps.package.outputs.content }}"



    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build



