name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
        
        
    - name: Restore Gradle user env && Update API KEY from Secrets
      env:
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      shell: bash
      run: |
       mkdir -p ~/.gradle/
       echo "GRADLE_USER_HOME=$HOME/.gradle" >> $GITHUB_ENV
       echo ls /home/runner/work/Android-Unslpash-s-Photo-Fetcher/Android-Unslpash-s-Photo-Fetcher
       echo UNSPLASH_API_KEY="$UNSPLASH_API_KEY" > /home/runner/work/Android-Unslpash-s-Photo-Fetcher/Android-Unslpash-s-Photo-Fetcher/gradle.properties  
       echo android.enableJetifier=true >/home/runner/work/Android-Unslpash-s-Photo-Fetcher/Android-Unslpash-s-Photo-Fetcher/gradle.properties  
       echo android.useAndroidX=true > /home/runner/work/Android-Unslpash-s-Photo-Fetcher/Android-Unslpash-s-Photo-Fetcher/gradle.properties
           
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    
     
