name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18

    - name: Restore Gradle user env && Update API KEY from Secrets
      env:
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
       mkdir -p ~/.gradle/
       echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
       echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
       echo UNSPLASH_API_KEY="$UNSPLASH_API_KEY" > ~/.gradle/local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build



