name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      
    - name: Update API KEY from Secrets
      env:
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      run: echo UNSPLASH_API_KEY="$UNSPLASH_API_KEY" > ./gradle.properties && echo android.enableJetifier=true > ./gradle.properties && echo android.useAndroidX=true > ./gradle.properties
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    
     
